export const LOADING_INVITATIONS = "LOADING_INVITATIONS";
export const SET_INVITATIONS = "SET_INVITATIONS";
export const GET_INVITATIONS = "GET_INVITATIONS";

export const LOADING_INVITATION = "LOADING_INVITATION";
export const SET_INVITATION = "SET_INVITATION";
export const GET_INVITATION = "GET_INVITATION";
export const CREATE_INVITATION = "CREATE_INVITATION";
export const DELETE_INVITATION = "DELETE_INVITATION";
export const EDIT_INVITATION = "EDIT_INVITATION";

export const LIKE_INVITATION = "LIKE_INVITATION";
export const UNLIKE_INVITATION = "UNLIKE_INVITATION";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
